window.migrationData = {
  version: "2026-05-22-orders-1",
  ordersPath: "orders-migration.generated.json",
  customers: [
    {
      id: "customer-cute-tomato",
      customerName: "Cute Tomato Hospitality LLP",
      customerCode: "REST_S_01",
      mapLink: "",
      contactName: "",
      contactNumber: "",
      billing: {
        organization: "Cute Tomato Hospitality LLP",
        address: "Paper Mill Compound, Metro City Centre\nNishatganj\nLucknow, Uttar Pradesh, 226006",
        gst: "09AASFC9850E1ZY",
        phone: "9118121555",
        paymentCycle: "30 days",
      },
      chefs: [],
    },
    {
      id: "customer-molecule-air-bar",
      customerName: "Molecule Air Bar",
      customerCode: "REST_M_01",
      mapLink: "",
      contactName: "",
      contactNumber: "",
      billing: {
        organization: "Molecule Air Bar",
        address: "3, Vipin Khand\nGomti Nagar, Lucknow, Uttar Pradesh",
        gst: "09AAACO9I3L1ZE",
        phone: "9305942060",
        paymentCycle: "45 days",
      },
      chefs: [],
    },
    {
      id: "customer-nai-coffee-hazratganj",
      customerName: "NAI COFFEE PRIVATE LIMITED",
      customerCode: "REST_R_01",
      mapLink: "",
      contactName: "",
      contactNumber: "",
      billing: {
        organization: "NAI COFFEE PRIVATE LIMITED",
        address: "12, Jahangirabad Palace\nRana Laxmibhai Marg, Hazratganj\nLucknow, Uttar Pradesh, 226001",
        gst: "09AAHC5928J1ZY",
        phone: "9559060424",
        paymentCycle: "30 days",
      },
      chefs: [],
    },
    {
      id: "customer-nai-coffee-gomti-nagar",
      customerName: "NAI COFFEE PRIVATE LIMITED",
      customerCode: "REST_R_02",
      mapLink: "",
      contactName: "",
      contactNumber: "",
      billing: {
        organization: "NAI COFFEE PRIVATE LIMITED",
        address: "7/158, Gomti Nagar, Vivek Khand\nLucknow, Uttar Pradesh, 226010",
        gst: "09AAHC5928J1ZY",
        phone: "8471016723",
        paymentCycle: "30 days",
      },
      chefs: [],
    },
    {
      id: "customer-fosho",
      customerName: "FOSHO",
      customerCode: "REST_F_01",
      mapLink: "",
      contactName: "",
      contactNumber: "",
      billing: {
        organization: "FOSHO",
        address: "11, Habibullah Estate\nHazratganj\nLucknow, Uttar Pradesh, 226001",
        gst: "09AAMCB4102H1ZU",
        phone: "7753851777",
        paymentCycle: "Due by 25th of the month",
      },
      chefs: [],
    },
  ],
};
